### ISSUE TITLE
Unable to download the source following the example code

### ISSUE THREAD

**Issue by jzhang28** [qpliu/qrencode-go#2]
go get github.com/qpliu/qrencode-go falls into error:
can't load package: package github.com/qpliu/qrencode-go: no buildable Go source files in ....
I found your source code are all moved into a subfolder "github.com/qpliu/qrencode-go/qrencode".

In addition, suggest to provide an example in the doc.  Below is copied out from your test case

```
grid, err := Encode("Testing one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty.", ECLevelQ)
if err != nil {
    return
}
f, err := os.Create("/tmp/qr.png")
if err != nil {
    return
}
defer f.Close()
png.Encode(f, grid.Image(8))
```

**Comment by qpliu** [comment]
Example added.  The package is "github.com/qpliu/qrencode-go/qrencode".
